/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "getSetFunctions.h"
#include <ecore.h>

typedef struct _uib_view1_control_context {
 /* add your variables here */

} uib_view1_control_context;

void view1_button1_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
// TCP port 8893 /* set thermostat des tmp(%f) */
	elm_object_text_set(vc->button1, "heating");

	//  this was just a test to see if tcp/ip comm was working, not currently working

	//int temp = 80;
	//set_temp(temp);

	char msg[] = "set thermostat des 80";

	var webSocketUrl = "http://10.18.81.7";

	var webSocket = new WebSocket(webSocketURL);

	/* If the connection is established */
	webSocket.onopen = function(e)
	{
	   console.log('connection open, readyState: ' + e.target.readyState);
	};

	/* If the connection fails or is closed with prejudice */
	webSocket.onerror = function(e)
	{
	   /* Error handling */
	};

	function sendMessage(msg)
	{
	   if (webSocket.readyState === 1)
	   {
	      webSocket.send(msg);
	   }
	};

	webSocket.onclose = function(e)
	{
	   console.log('connection close, readyState: ' + e.target.readyState);
	};

	function closeConnection()
	{
	   if (webSocket.readyState === 1)
	   {
	      webSocket.close();
	   }
	};
}

void view1_button1_onunpressed(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	elm_object_text_set(vc->button1, "temp");
}

void view1_button1_onrepeated(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	elm_object_text_set(vc->button1, "cooling");
}

